### ISSUE TITLE
Debian Installation Faile

### ISSUE THREAD

**Issue by hackern0v1c3** [jimsalterjrs/sanoid#379]
I am trying to install sanoid on an openmediavault server which is based on debian.  When I follow the debian instructions I am able to build the .deb files but when I try to install them I get the following error related to the unit file.  I am logged in as root.  Then I'm unable to start the timer because the service was not created.  I'm not really sure how to troubleshoot this.  Any help would be appreciated.

 ```
apt install ../sanoid_*_all.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'sanoid' instead of '../sanoid_2.0.0_all.deb'
The following NEW packages will be installed:
  sanoid
0 upgraded, 1 newly installed, 0 to remove and 15 not upgraded.
Need to get 0 B/36.7 kB of archives.
After this operation, 161 kB of additional disk space will be used.
Get:1 /root/sanoid_2.0.0_all.deb sanoid all 2.0.0 [36.7 kB]
Selecting previously unselected package sanoid.
(Reading database ... 83204 files and directories currently installed.)
Preparing to unpack /root/sanoid_2.0.0_all.deb ...
Unpacking sanoid (2.0.0) ...
Setting up sanoid (2.0.0) ...
Created symlink /etc/systemd/system/sanoid.service.wants/sanoid-prune.service → /lib/systemd/system/sanoid-prune.service.
Failed to get unit file state for sanoid.timer: No such file or directory
sanoid.timer is a disabled or a static unit, not starting it.
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f23ff3f0620>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f23ff3f0620>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
N: Download is performed unsandboxed as root as file '/root/sanoid_2.0.0_all.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)

```

**Comment by phreaker0** [comment]
This should be solved by #370.

**Comment by KevinGage** [comment]
Thanks for taking the time to get back to me.  Unfortunatly that doesn't seem to be the issue in my case.  See below.

`root@openmediavault:~# apt-get install debhelper
Reading package lists... Done
Building dependency tree
Reading state information... Done
debhelper is already the newest version (10.2.5).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
root@openmediavault:~# ls
emby_backup.log           rsync.log  sanoid_2.0.0_all.deb          sanoid_2.0.0_amd64.changes  sanoid_2.0.0.tar.xz
emby_media_nas_backup.sh  sanoid     sanoid_2.0.0_amd64.buildinfo  sanoid_2.0.0.dsc            seafile_database_backup.sh
root@openmediavault:~# cd sanoid/
root@openmediavault:~/sanoid# ls
CHANGELIST  findoid         INSTALL.md  packages   sanoid       sanoid.defaults.conf  syncoid  VERSION
debian      FREEBSD.readme  LICENSE     README.md  sanoid.conf  sleepymutex           tests
root@openmediavault:~/sanoid# git pull
Already up-to-date.
root@openmediavault:~/sanoid# apt install libconfig-inifiles-perl pv lzop mbuffer debhelper
Reading package lists... Done
Building dependency tree
Reading state information... Done
debhelper is already the newest version (10.2.5).
libconfig-inifiles-perl is already the newest version (2.94-1).
lzop is already the newest version (1.03-4+b1).
mbuffer is already the newest version (20161115-1).
pv is already the newest version (1.6.0-1+b1).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
root@openmediavault:~/sanoid# dpkg-buildpackage -uc -us
dpkg-buildpackage: info: source package sanoid
dpkg-buildpackage: info: source version 2.0.0
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Jim Salter <github@jrs-s.net>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build sanoid
 debian/rules clean
dh clean --with systemd
   dh_testdir
   dh_auto_clean
   dh_clean
 dpkg-source -b sanoid
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building sanoid in sanoid_2.0.0.tar.xz
dpkg-source: info: building sanoid in sanoid_2.0.0.dsc
 debian/rules build
dh build --with systemd
   dh_testdir
   dh_update_autotools_config
   dh_auto_configure
   dh_auto_build
   dh_auto_test
   create-stamp debian/debhelper-build-stamp
 debian/rules binary
dh binary --with systemd
   create-stamp debian/debhelper-build-stamp
   dh_testroot
   dh_prep
   debian/rules override_dh_auto_install
make[1]: Entering directory '/root/sanoid'
make[1]: Leaving directory '/root/sanoid'
   dh_installdocs
   dh_installchangelogs
   debian/rules override_dh_systemd_enable
make[1]: Entering directory '/root/sanoid'
dh_systemd_enable sanoid.timer
dh_systemd_enable: Could not find "sanoid.timer" in the /lib/systemd/system directory of sanoid. This could be a typo, or using Also= with a service file from another package. Please check carefully that this message is harmless.
dh_systemd_enable: Cannot open(sanoid.timer) for extracting the Also= line(s)
dh_systemd_enable sanoid-prune.service
make[1]: Leaving directory '/root/sanoid'
   debian/rules override_dh_installinit
make[1]: Entering directory '/root/sanoid'
dh_installinit --noscripts
make[1]: Leaving directory '/root/sanoid'
   debian/rules override_dh_systemd_start
make[1]: Entering directory '/root/sanoid'
dh_systemd_start sanoid.timer
dh_systemd_start: Could not find "sanoid.timer" in the /lib/systemd/system directory of sanoid. This could be a typo, or using Also= with a service file from another package. Please check carefully that this message is harmless.
dh_systemd_start: Cannot open(sanoid.timer) for extracting the Also= line(s)
dh_systemd_start: Cannot open(sanoid.timer) for extracting the Also= line(s)
make[1]: Leaving directory '/root/sanoid'
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_installdeb
   dh_gencontrol
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'sanoid' in '../sanoid_2.0.0_all.deb'.
 dpkg-genbuildinfo
 dpkg-genchanges  >../sanoid_2.0.0_amd64.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build sanoid
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
root@openmediavault:~/sanoid# apt install ../sanoid_*_all.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'sanoid' instead of '../sanoid_2.0.0_all.deb'
sanoid is already the newest version (2.0.0).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.`

**Comment by Xonzo** [comment]
Experiencing the same deb installation failure. 

`
dh_systemd_enable: Could not find "sanoid.timer" in the /lib/systemd/system directory of sanoid. This could be a typo, or using Also= with a service file from another package. Please check carefully that this message is harmless.
dh_systemd_enable: Cannot open(sanoid.timer) for extracting the Also= line(s)
dh_systemd_enable sanoid-prune.service
make[1]: Leaving directory '/tmp/sanoid'
   debian/rules override_dh_installinit
make[1]: Entering directory '/tmp/sanoid'
dh_installinit --noscripts
make[1]: Leaving directory '/tmp/sanoid'
   debian/rules override_dh_systemd_start
make[1]: Entering directory '/tmp/sanoid'
dh_systemd_start sanoid.timer
dh_systemd_start: Could not find "sanoid.timer" in the /lib/systemd/system directory of sanoid. This could be a typo, or using Also= with a service file from another package. Please check carefully that this message is harmless.
dh_systemd_start: Cannot open(sanoid.timer) for extracting the Also= line(s)
dh_systemd_start: Cannot open(sanoid.timer) for extracting the Also= line(s)
`

**Comment by phreaker0** [comment]
There is a permission error in your log, the apt user can't access the package apparently becaus it's located in /root. Please try again with an updated openmediavault (as the basis ist debian9.1 it should just work) and use a package location where every user can access the deb file.

**Comment by Lefuneste83** [comment]
I confirm this issue still exists when installing from /root on Proxmox (Debian). Doing the same installation procedure from a less restricted directory such as /tmp solves this issue. Maybe a small note should be added to the installation procedure for Debian based distros.
